name: Part 11 Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout part11 only
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            part11
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./part11/full-stack-open-pokedex
        run: npm install
      - name: Check lint style
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run eslint
      - name: Run build
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run build
      - name: Run Jest tests
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run test
      - name: Install Playwright Browsers
        working-directory: ./part11/full-stack-open-pokedex
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./part11/full-stack-open-pokedex
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
