name: Part 11 Deployment checkup

on:
  schedule:
    - cron: "00 6 * * *"
  workflow_dispatch:

jobs:
  checkup_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout part11 deployment on Render
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-u6ry.onrender.com/health
          max-attempts: 3
          retry-delay: 5s